version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./frontend:/home/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - identity_provider
    environment:
      - HYDRA_AUTH_URL=http://tokyo.localhost:9000/oauth2/auth?client_id=tokyo&response_type=code&state=72582c142d403a972b579f05140bf93f&nonce=gyukgyglgghjjkk&redirect_uri=http://tokyo.localhost:3000/sessions/callback&scope=openid+offline
      - CLIENT_ID=tokyo
      - CLIENT_SECRET=secret
      - AUTH_STATE=72582c142d403a972b579f05140bf93f
      - DB_PASSWORD=secret
      - DB_HOST=db

  identity_provider:
    build:
      context: ./identity_provider
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./identity_provider:/home/app
    depends_on:
      - db
      - hydra
    ports:
      - "4000:3000"
    environment:
      - HYDRA_URL=http://hydra:4444
      - HYDRA_ADMIN_URL=http://hydra:4445
      - DB_PASSWORD=secret
      - DB_HOST=db

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  hydra:
    image: oryd/hydra:v1.0.0-rc.7_oryOS.10
    ports:
      - "9000:4444"
      - "4445:4445"
    command:
      serve all --dangerous-force-http
    environment:
      - ISSUER=http://tokyo.localhost:9000
      - OAUTH2_ISSUER_URL=http://tokyo.localhost:9000
      - OAUTH2_CONSENT_URL=http://tokyo.localhost:4000/consent
      - OAUTH2_LOGIN_URL=http://tokyo.localhost:4000/login
      - SYSTEM_SECRET=YSwy2MAEt7gALtW~uJC3x_3mWZ_CNRC0
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - DATABASE_URL=memory
    restart: unless-stopped

volumes:
  db_data:
